fix some problems listed by golangci-lint
clusternet/clusternet pull request #88
Opened 2021-08-30 08:32 UTC by hezhizhen

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

2021-08-30 09:44 UTC, dixudx commented
@hezhizhen Please adding your golang lint rules as well. This would help make CIs happier.

2021-08-30 12:29 UTC, dixudx requested changes

2021-08-30 12:29 UTC, dixudx commented on .golangci.yml
> +    - structcheck
Prefer to add to https://github.com/clusternet/clusternet/blob/main/Makefile#L53

2021-08-30 14:01 UTC, dixudx reviewed
Excellent work!

2021-08-30 14:01 UTC, dixudx commented on Makefile
> +      -E ineffassign \
inconsistent indents.

Please correct them. Thanks

2021-08-30 14:04 UTC, dixudx commented on Makefile
> +      -E ineffassign \
Line 61-68 vs Line 60

2021-08-31 03:06 UTC, hezhizhen commented on Makefile
> +      -E ineffassign \
PTAL

2021-08-31 03:25 UTC, hezhizhen commented
I'll fix other problems in the afternoon.

2021-08-31 04:29 UTC, merged